name: Example Workflow

on: [push, pull_request]

jobs:
  #Job Name
  minitest:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install Ruby
        uses: ruby/setup-ruby@v2
        with:
          bundler-cache: true


      - name: Bundle Install
        run: bundle install

      - name: Run minitest
        run: bin/rails test:system
    
